### PR TITLE
Display menu item form errors

### LINKED ISSUE #4547: Navigation item without a link breaks the dashboard
### Steps to reproduce the problem
1. In Dashboard 2.0 go to Configure > Navigation > go to a menu details page.
2. Click "Add new item"
3. Fill only the "name" field and click "submit".
4. Click on the "edit" button for the newly created item.

### What I expected to happen
A modal to edit the menu item should be opened.

Also when trying to create an empty menu item, the error returned from API is not handled properly - the "submit" button goes into "error" state but the error message is not displayed anywhere.

### PR DESCRIPTION
**Pull request by dominik-zeglen**
I want to merge this change because it fixes error displaying and empty value handling in menu item dialog.
Fixes #4547 

### Screenshots
Screenshot 2019-07-29 at 13 14 33
Screenshot 2019-07-29 at 13 29 02

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by django-queries** [comment]
Here is the report for bd2b27e4b2c80c9dc45b5d63a4c0351549ded456 (mirumee/saleor @ fix/display-menu-errors)
Base comparison is cf43e0e604c88a84606e8cc0fd6bee84bb660079.



<details><summary>No differences were found. (click me)</summary>
<p>

```diff
# api.benchmark checkout
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  add billing address to checkout     	         34	         34	             20
  add shipping to checkout            	          7	          7	              0
  checkout payment charge             	         14	         14	              0
  complete checkout                   	          6	          6	              0
  create checkout                     	         41	         41	             20

# api.benchmark homepage
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  retrieve main menu                  	          5	          5	              0
  retrieve product list               	          4	          4	              0
  retrieve secondary menu             	          5	          5	              0
  retrieve shop                       	          2	          2	              0

# api.benchmark product
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  product details                     	         13	         13	              3

# api.benchmark variant
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  retrieve variant list               	          9	          9	              2
```

</p>
</details>

File: saleor/static/dashboard-next/hooks/useStateFromProps.ts [hunk 1]
```diff
@@ -8,14 +8,16 @@ export interface UseStateFromPropsOpts<T> {
...
 function useStateFromProps<T>(
   data: T,
-  opts: UseStateFromPropsOpts<T>
+  opts?: UseStateFromPropsOpts<T>
 ): [T, Dispatch<SetStateAction<T>>] {
   const [state, setState] = useState(data);
   const [prevData, setPrevData] = useState(data);
-
-  const { mergeFunc, onRefresh } = opts;
+  if (!opts) {
```
Comment (benekex2) [inline saleor/static/dashboard-next/hooks/useStateFromProps.ts]: Unnecessary braces

File: saleor/static/dashboard-next/hooks/useModalDialogErrors/useModalDialogErrors.ts [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+function useModalDialogErrors<TError>(
+  errors: TError[],
+  open: boolean
+): TError[] {
+  const [state, setState] = useStateFromProps(errors);
+  const [prevOpenState, setPrevOpenstate] = useState(open);
+
+  if (open !== prevOpenState) {
+    setPrevOpenstate(open);
+    if (!open) {
```
Comment (benekex2) [inline saleor/static/dashboard-next/hooks/useModalDialogErrors/useModalDialogErrors.ts]: Unnecessary braces
