### PR TITLE
Fix storefront issues

### LINKED ISSUE #865: Front end storefront fixes
- [x] add bigger active area to close button in search form on mobile

### PR DESCRIPTION
**Pull request by benekex2**
Fix #865

### CODE REVIEW

File: saleor/static/js/components/categoryPage/ProductPrice.js [hunk 1]
```diff
@@ -11,7 +13,7 @@ const ProductPrice = ({ availability, price }) => {
         {isPriceRange && <span>{gettext('from')} </span>} {gross}
       </span>
       {discount && (
-        <div className="product-list__sale"><span>Sale</span></div>
+        <div className="product-list__sale"><img src={SaleImg}/><span>Sale</span></div>
```
Comment (elwoodxblues) [inline saleor/static/js/components/categoryPage/ProductPrice.js]: We miss a translation here. It should be `{gettext('Sale')}`. See how we use `gettext` in JS in other modules for reference.
