### PR TITLE
Front end and copy fixes

### LINKED ISSUE #713: Improve price ranges display - use 'from 50 USD' instead of '50 USD +'

### LINKED ISSUE #714: Checkout billing address - don't use bold

### LINKED ISSUE #715: Fix form labels align on checkout thank you page.
Labels for password set form should be aligned to left.

### LINKED ISSUE #716: Improve navigation labels in checkout call to action buttons
Labels should simple and verbose, for example:
- `Continue` instead of `Continue to shipping address`
- `Order & Pay` instead of `Place order`

### LINKED ISSUE #717: Add checkout steps navigation
Now there's no explicit navigation. Using browser back button can be dangerous in some cases and it's not a common behavior in ecommerce

### PR DESCRIPTION
**Pull request by weronka**
Fix #716
Fix #715
Fix #714
Fix #713
Fix #717

### CODE REVIEW

**Comment by artursmet** [comment]
On checkout, there's another label with wrong content 'Continue to payment' on shipping method step. I'd recommend to rename it also to 'continue'

File: saleor/static/js/storefront.js [hunk 1]
```diff
@@ -156,6 +169,19 @@ $countrySelect.on('change', (e) => {
   })
 })
 
+// Save tab links to URL
+  		  
+$('.nav-tabs a').click((e) => {
+  e.preventDefault()
+  $(this).tab('show')
+});
+$("ul.nav-tabs li a:not(:first)").on("shown.bs.tab", (e) => {
```
Comment (benekex2) [inline saleor/static/js/storefront.js]: Use single quotes
