### PR TITLE
Fix visibility card view

### LINKED ISSUE #4137: "Visibility" Card - Logic and Frontend Changes
We need to change "Availability" Card title to "Visibility" as it was reported as confusing. 
We should also change the logic behind how publishing elements work according to design.

### PR DESCRIPTION
**Pull request by benekex2**
Resolves #4137 

I want to merge this change because...

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by maarcingebala** [comment]
I've spotted one wording issue - if the publication date is set in the past and you'll change the switch to "hidden" you'll get the message that is logically incorrect "Will be visible on <date in the past>":

image

Maybe we'd have to check if visibility is set to "hidden" and the publication date is in the past, then we should simply say "hidden"?

File: saleor/static/dashboard-next/pages/components/PageDetailsPage/PageDetailsPage.tsx [hunk 1]
```diff
@@ -112,9 +112,9 @@ const PageDetailsPage: React.StatelessComponent<PageDetailsPageProps> = ({
                 onChange={change}
               />
               <CardSpacer />
-              <PageAvailability
+              <VisibilityCard
                 data={data}
-                disabled={disabled}
+                loading={disabled}
```
Comment (dominik-zeglen) [inline saleor/static/dashboard-next/pages/components/PageDetailsPage/PageDetailsPage.tsx]: ...but why?
It would make sense if you'd show skeleton instead of target component, but all you achieved with this change is this prop flow: `disabled => loading => disabled`

File: saleor/static/dashboard-next/components/VisibilityCard/VisibilityCard.tsx [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+  });
+
+interface VisibilityCardProps extends WithStyles<typeof styles> {
+  children?: React.ReactNode;
+  data: {
+    isPublished: boolean;
+    publicationDate: string;
+  };
+  errors: { [key: string]: string };
+  loading?: boolean;
```
Comment (dominik-zeglen) [inline saleor/static/dashboard-next/components/VisibilityCard/VisibilityCard.tsx]: I'd rather explicitly set `false` here rather than let someone forget about this prop

File: saleor/static/dashboard-next/components/VisibilityCard/VisibilityCard.tsx [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+  onChange(event: any);
+}
+
+export const VisibilityCard = withStyles(styles, {
+  name: "PVisibilityCard"
```
Comment (dominik-zeglen) [inline saleor/static/dashboard-next/components/VisibilityCard/VisibilityCard.tsx]: Typo

File: saleor/static/dashboard-next/components/VisibilityCard/VisibilityCard.tsx [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+    expandedSwitchContainer: {
+      marginBottom: 0
+    },
+    switchContainer: {
+      marginBottom: -theme.spacing.unit
+    }
+  });
+
+interface VisibilityCardProps extends WithStyles<typeof styles> {
+  children?: React.ReactNode;
```
Comment (dominik-zeglen) [inline saleor/static/dashboard-next/components/VisibilityCard/VisibilityCard.tsx]: `React.ReactNode | React.ReactNodeArray` would be better since this component passes no props to its children

File: saleor/static/dashboard-next/components/VisibilityCard/VisibilityCard.tsx [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+            }
+          >
+            <ControlledSwitch
+              name="isPublished"
+              label={i18n.t("Visible")}
+              uncheckedLabel={i18n.t("Hidden")}
+              secondLabel={
+                publicationDate
+                  ? isPublished
+                    ? i18n.t("since ") + publicationDate
```
Comment (dominik-zeglen) [inline saleor/static/dashboard-next/components/VisibilityCard/VisibilityCard.tsx]:
```
i18n.t("since { date }", {
  date: publicationDate
})
```

File: saleor/static/dashboard-next/components/VisibilityCard/VisibilityCard.tsx [hunk 6]
```diff
@@ -0,0 +1,111 @@
...
+                    : Date.parse(publicationDate) > Date.now()
+                    ? i18n.t("will be visible on ") + publicationDate
```
Comment (dominik-zeglen) [inline saleor/static/dashboard-next/components/VisibilityCard/VisibilityCard.tsx]: Same

File: saleor/static/dashboard-next/products/components/ProductAvailabilityForm/ProductAvailabilityForm.tsx [hunk 7]
```diff
@@ -16,7 +16,10 @@ import i18n from "../../../i18n";
 const styles = (theme: Theme) =>
   createStyles({
     date: {
-      marginTop: theme.spacing.unit
+      "& svg": {
```
Comment (dominik-zeglen) [inline saleor/static/dashboard-next/products/components/ProductAvailabilityForm/ProductAvailabilityForm.tsx]: Isn't it a copy of `saleor/static/dashboard-next/components/VisibilityCard/VisibilityCard.tsx`?
