### PR TITLE
Escape IDs

### LINKED ISSUE #2657: Escape IDs in urls
### What I'm trying to achieve
To fix a potential router crash when objects ID contains slash (which could happen, since base64 allows it), matching as ID only its part.

### Steps to reproduce the problem
1. Find an object, whose ID contains the slash character
2. Go to its details page
3. Contemplate the error

### What I expected to happen
To display the details page instead of an error.

### Proposed solution
Use `encodeURIComponent()` where applicable.

### PR DESCRIPTION
**Pull request by dominik-zeglen**
Resolves #2657

### CODE REVIEW

File: saleor/static/dashboard-next/categories/index.tsx [hunk 1]
```diff
@@ -12,20 +12,25 @@ const CategoryPaginator: React.StatelessComponent<RouteComponentProps<any>> = ({
 }) => {
   const qs = parseQs(location.search.substr(1));
   const params = {
-    after: qs.after,
-    before: qs.before
+    after: decodeURIComponent(qs.after),
```
Comment (patrys) [inline saleor/static/dashboard-next/categories/index.tsx]: Shouldn't this be handled by `qs.parse()`?

File: saleor/static/dashboard-next/orders/index.tsx [hunk 2]
```diff
@@ -22,7 +22,7 @@ const OrderList: React.StatelessComponent<RouteComponentProps<any>> = ({
 const OrderDetails: React.StatelessComponent<RouteComponentProps<any>> = ({
   match
 }) => {
-  return <OrderDetailsComponent id={match.params.id} />;
+  return <OrderDetailsComponent id={decodeURIComponent(match.params.id)} />;
```
Comment (patrys) [inline saleor/static/dashboard-next/orders/index.tsx]: How is this not decoded already?

File: saleor/static/dashboard-next/orders/views/OrderDetails.tsx [hunk 3]
```diff
@@ -558,7 +560,9 @@ export const OrderDetails: React.StatelessComponent<OrderDetailsProps> = ({
                                     label: country.country
                                   }))}
                                   onProductClick={id => () =>
-                                    navigate(productUrl(id))}
+                                    navigate(
+                                      productUrl(encodeURIComponent(id))
```
Comment (patrys) [inline saleor/static/dashboard-next/orders/views/OrderDetails.tsx]: The `productUrl` function should be responsible for that.

File: saleor/static/dashboard-next/orders/views/OrderList.tsx [hunk 4]
```diff
@@ -30,7 +30,9 @@ export const OrderList: React.StatelessComponent<OrderListProps> = ({
             pushMessage({
               text: i18n.t("Order draft succesfully created")
             });
-            navigate(orderUrl(data.draftOrderCreate.order.id));
+            navigate(
+              orderUrl(encodeURIComponent(data.draftOrderCreate.order.id))
```
Comment (patrys) [inline saleor/static/dashboard-next/orders/views/OrderList.tsx]: The `orderUrl` function should be responsible for that.

File: saleor/static/dashboard-next/productTypes/index.tsx [hunk 5]
```diff
@@ -13,14 +13,10 @@ export const productTypeListUrl = "/productTypes";
 const ProductTypeList: React.StatelessComponent<RouteComponentProps<{}>> = ({
   location
 }) => {
-  const queryString = parseQs(location.search.substr(1));
+  const qs = parseQs(location.search.substr(1));
   const params = {
```
Comment (patrys) [inline saleor/static/dashboard-next/productTypes/index.tsx]: How about:

```
const { after, before } = qs;

...

return <ProductTypeListComponent params={{ after, before }} />;
```

And if we're here, why is there `params` instead of explicitly accepting `after` and `before` as props?
