### PR TITLE
Fix saving button

### LINKED ISSUE #3129: Dashboard 2.0- Submit button shows "Saving" label when loading the view for the first time
"Save" button shows the "Saving" label with spinner when a view is being loaded for the first time. I assume that the `isLoading` state from Apollo is naivly passed to the button component, which in this case should happen only when a mutation is triggered. This happens for example in the new category details view (currently `Restyle/categories-section` branch), but I suppose it happens in other views as well. 

image

### PR DESCRIPTION
**Pull request by dominik-zeglen**
I want to merge this change because it fixes broken submit button and adds loading (and success / error) state to it.
Resolves #3129 

### Pull Request Checklist

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.

### CODE REVIEW

File: saleor/static/dashboard-next/pages/views/PageDetails.tsx [hunk 1]
```diff
@@ -33,102 +31,88 @@ export class PageUpdateForm extends React.Component<
...
-                        }
-                        return <Redirect to={pageListUrl} />;
+                if (
+                  deleteResult.pageDelete.errors &&
+                  deleteResult.pageDelete.errors.length
+                ) {
+                  console.error(deleteResult.pageDelete);
+                  return;
+                }
+                // FIXME: component is loaded with previous state (meaning that deleted page will still be there until table reload)
```
Comment (maarcingebala) [inline saleor/static/dashboard-next/pages/views/PageDetails.tsx]: Perhaps we should add an issue for that.

File: saleor/static/dashboard-next/pages/views/PageDetails.tsx [hunk 2]
```diff
@@ -33,102 +31,88 @@ export class PageUpdateForm extends React.Component<
...
-                        if (error) {
-                          console.error(error);
-                          return;
-                        }
-                        return <Redirect to={pageListUrl} />;
+                if (
+                  deleteResult.pageDelete.errors &&
+                  deleteResult.pageDelete.errors.length
+                ) {
+                  console.error(deleteResult.pageDelete);
```
Comment (maarcingebala) [inline saleor/static/dashboard-next/pages/views/PageDetails.tsx]: I think we can get rid of all `console.error` - we'll show a message that something failed and the developer would debug this in browser developer tools anyway.

File: saleor/static/dashboard-next/pages/views/PageDetails.tsx (hunk 1 above)
Comment (dominik-zeglen) [reply saleor/static/dashboard-next/pages/views/PageDetails.tsx]: No need; bug was fixed with an introduction of `<TypedQuery />`. I'll remove this comment.
