### PR TITLE
Dashboard front-end improvements

### LINKED ISSUE #502: Tables don't like to be resized
Order details:

image

### LINKED ISSUE #514: Product images dropzone doesn't work if there are no images
When I'm trying to add some images to a product that currently doesn't have one, the dropzone doesn't work, because the image is just opened in a new tab, instead of getting uploaded. When there is already any image in the list, the dropzone works correctly.

### LINKED ISSUE #566: Dashboard front-end improvements
- [x] open dashboard and storefront in separate tabs
- [x] fix datepicker
- [x] responsive breakpoints need to be fixed
- [x] fix inputs grid 
- [x] add drag and drop icon to sorting elements for better mobile scrolling experience
- [x] fix order filter form
- [x] show products in category view

### PR DESCRIPTION
**Pull request by weronka**
Fix #566
Fix #502
Fix #514

### CODE REVIEW

**Comment by patrys** [comment]
We can't display all products from a given category like that. What if there is >1000 of them?

File: saleor/static/js/dashboard.js [hunk 1]
```diff
@@ -171,7 +171,10 @@ $('.datepicker').pickadate({
   format: 'd mmmm yyyy',
   formatSubmit: 'yyyy-mm-dd',
   selectMonths: true,
-  hiddenName: true
+  hiddenName: true,
+  onClose: function() {
+        $(document.activeElement).blur();
```
Comment (patrys) [inline saleor/static/js/dashboard.js]: We're using 2 spaces for indentation in JS

File: templates/dashboard/product/product_form.html [hunk 2]
```diff
@@ -273,16 +273,15 @@
...
+        <div id="images" class="tab-content">            
                 <div class="row">
                     <div class="col l12">
                         <form action="{% url 'dashboard:product-images-upload' product_pk=product.pk %}" class="dropzone" id="product-image-form">
                             <div class="dz-message"></div>
                             {% csrf_token %}
                             <input type="hidden" name="success_url" value="{% url 'dashboard:product-update' pk=product.pk %}#images">
-
                             <ul class="row product-gallery" id="product-gallery" data-post-url="{% url 'dashboard:product-images-reorder' product_pk=product.pk %}">
+                              {% if images %}
```
Comment (patrys) [inline templates/dashboard/product/product_form.html]: Could you fix indentation of this and its `else`/`endif` tags?
